{ pkgs }:

# win-vm — CLI wrapper around libvirt/virt-install for the Windows 11
# desktop test VM.
#
# Microsoft's Win11 ISO is fetched via a per-session URL generated by
# https://www.microsoft.com/software-download/windows11 — that URL
# expires after ~24h and there is no stable direct link, so this
# wrapper does NOT scrape MS. Grab a fresh URL by hand, feed it to
# `win-vm fetch-iso <url>`, then `win-vm create` to define the VM.
#
# VM shape:
#   Q35 + UEFI + TPM 2.0 (all three Win11 install requirements),
#   4 vCPU host-passthrough, 8 GiB RAM, 60 GiB qcow2, virtio disk +
#   virtio-net, SPICE graphics + ich9 audio, qemu-xhci USB.
pkgs.writeShellApplication {
  name = "win-vm";
  runtimeInputs = with pkgs; [
    libvirt
    virt-viewer
    curl
    coreutils
    qemu_kvm
  ];
  text = ''
    set -euo pipefail

    IMG_DIR=/var/lib/libvirt/images
    ISO="$IMG_DIR/Win11.iso"
    DISK="$IMG_DIR/win11.qcow2"
    VM=win11
    URI=qemu:///system

    die() { echo "win-vm: $*" >&2; exit 1; }
    log() { echo "win-vm: $*" >&2; }

    usage() {
      cat >&2 <<'HELP'
Usage:
  win-vm fetch-iso <url>   download Win11 ISO to /var/lib/libvirt/images/Win11.iso
                           Get a fresh URL from:
                             https://www.microsoft.com/software-download/windows11
                           (URLs expire in ~24h — grab and use immediately.)

  win-vm create            define the win11 VM in libvirt + start install boot
                           (requires the ISO to exist)

  win-vm view              attach virt-viewer to the running VM (SPICE)
  win-vm start             start the VM (if defined + shut off)
  win-vm stop              graceful shutdown
  win-vm destroy           force-off (like pulling the plug)
  win-vm undefine          remove VM definition + disk (destructive)
  win-vm status            virsh domstate + disk sizes

Runs against qemu:///system — you must be in the libvirtd group.
HELP
    }

    require_group() {
      if ! id -nG | tr ' ' '\n' | grep -qx libvirtd; then
        die "you are not in the libvirtd group — log out + back in after the module lands, or run 'newgrp libvirtd'"
      fi
    }

    cmd="''${1:-help}"
    shift || true

    case "$cmd" in
      fetch-iso)
        url="''${1:-}"
        [ -n "$url" ] || die "missing <url>. Get one from: https://www.microsoft.com/software-download/windows11"
        require_group
        mkdir -p "$IMG_DIR" 2>/dev/null || sudo mkdir -p "$IMG_DIR"
        log "downloading Win11 ISO to $ISO (~6 GiB)…"
        # -L follow redirects; -C - resume; -o output
        if ! curl -L -C - -o "$ISO" "$url"; then
          die "download failed. URL may have expired — grab a fresh one."
        fi
        size=$(stat -c '%s' "$ISO")
        # sanity floor: Win11 ISO is >4 GiB; anything smaller is a broken download
        if [ "$size" -lt 4000000000 ]; then
          die "ISO is only $size bytes — download truncated or wrong URL. Remove $ISO and retry."
        fi
        log "ok — $ISO ($size bytes)"
        ;;

      create)
        require_group
        [ -f "$ISO" ] || die "no ISO at $ISO — run 'win-vm fetch-iso <url>' first"
        if virsh --connect "$URI" dominfo "$VM" >/dev/null 2>&1; then
          die "VM '$VM' already defined. 'win-vm undefine' first if you want to recreate."
        fi
        log "creating VM '$VM' (Q35 + UEFI + TPM 2.0, 4 vCPU, 8 GiB RAM, 60 GiB disk)…"
        virt-install \
          --connect "$URI" \
          --name "$VM" \
          --memory 8192 \
          --vcpus 4 \
          --cpu host-passthrough \
          --machine q35 \
          --boot uefi \
          --tpm backend.type=emulator,backend.version=2.0,model=tpm-crb \
          --disk "path=$DISK,size=60,format=qcow2,bus=virtio" \
          --disk "path=$ISO,device=cdrom,bus=sata" \
          --network network=default,model=virtio \
          --graphics spice \
          --video qxl \
          --sound ich9 \
          --controller type=usb,model=qemu-xhci \
          --os-variant win11 \
          --noautoconsole
        log "VM created. Attach with: win-vm view"
        ;;

      view)     require_group; exec virt-viewer --connect "$URI" "$VM" ;;
      start)    require_group; virsh --connect "$URI" start "$VM" ;;
      stop)     require_group; virsh --connect "$URI" shutdown "$VM" ;;
      destroy)  require_group; virsh --connect "$URI" destroy "$VM" ;;
      undefine)
        require_group
        virsh --connect "$URI" destroy "$VM" 2>/dev/null || true
        virsh --connect "$URI" undefine "$VM" --nvram --remove-all-storage
        ;;
      status)
        require_group
        virsh --connect "$URI" dominfo "$VM" 2>/dev/null || echo "not defined"
        [ -f "$DISK" ] && du -h "$DISK"
        [ -f "$ISO" ]  && du -h "$ISO"
        ;;
      -h|--help|help) usage ;;
      *) usage; die "unknown subcommand: $cmd" ;;
    esac
  '';
}
